USE [master]
GO

/****** Object:  Database [International_BI_Store]    Script Date: 10/06/2026 16:14:27 ******/
CREATE DATABASE [International_BI_Store]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'International_BI_Store', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL17.MSSQLSERVER\MSSQL\DATA\International_BI_Store.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'International_BI_Store_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL17.MSSQLSERVER\MSSQL\DATA\International_BI_Store_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [International_BI_Store].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [International_BI_Store] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [International_BI_Store] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [International_BI_Store] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [International_BI_Store] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [International_BI_Store] SET ARITHABORT OFF 
GO

ALTER DATABASE [International_BI_Store] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [International_BI_Store] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [International_BI_Store] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [International_BI_Store] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [International_BI_Store] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [International_BI_Store] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [International_BI_Store] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [International_BI_Store] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [International_BI_Store] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [International_BI_Store] SET  ENABLE_BROKER 
GO

ALTER DATABASE [International_BI_Store] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [International_BI_Store] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [International_BI_Store] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [International_BI_Store] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [International_BI_Store] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [International_BI_Store] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [International_BI_Store] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [International_BI_Store] SET RECOVERY FULL 
GO

ALTER DATABASE [International_BI_Store] SET  MULTI_USER 
GO

ALTER DATABASE [International_BI_Store] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [International_BI_Store] SET DB_CHAINING OFF 
GO

ALTER DATABASE [International_BI_Store] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [International_BI_Store] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [International_BI_Store] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [International_BI_Store] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [International_BI_Store] SET OPTIMIZED_LOCKING = OFF 
GO

ALTER DATABASE [International_BI_Store] SET QUERY_STORE = ON
GO

ALTER DATABASE [International_BI_Store] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [International_BI_Store] SET  READ_WRITE 
GO

